### ISSUE TITLE
organiser les fichiers dans des dossiers, car c'est illisible !

### ISSUE THREAD

**Issue by loulou123546** [Info-Ormatique/website#1]
Franchement, faite des sous partie dans des dossiers :open_file_folder: , par exemple :

- acceuil.html
- w3.css
- android
  - index.html
  - style.css
- IOS
  - index.html
  - style.css

---

# Bref, ***Organisez vous !***

**Comment by loulou123546** [comment]
ok, j'ouvre un pull request ce soir.

**Comment by floflo37** [comment]
ok

**Comment by loulou123546** [comment]
l'organisation ne peut pas faite, la moitié de vos fichiers sont même pas utilisé, il y a des erreurs que même Kévin, 7 ans ne fait pas (voir #8 ), ...  bref, il y a des urgences à régler avant de mettre tout ça en place

**Comment by loulou123546** [comment]
Je reprend cette issue car j'ai trouvé un moyen pour bien vous organiser, **DONC PAS TOUCHE AU LIEN JUSQU'A ACCEPTATION DE LA PULL REQUEST !**

**Comment by loulou123546** [comment]
# PULL REQUEST EN #12 !

**Comment by loulou123546** [comment]
# PULL REQUEST #17 ACCEPTER ✔️
