### ISSUE TITLE
lien a ajouter

### ISSUE THREAD

**Issue by floflo37** [Info-Ormatique/website#10]
certaine page n'ont pas tous les liens sur leur menu

**Comment by loulou123546** [comment]
je suit en train de déplacer les fichier ( #1 ) donc pas touche au lien !

**Comment by loulou123546** [comment]
### Fini ?

**Comment by floflo37** [comment]
je suis en train de le faire

**Comment by loulou123546** [comment]
ok

**Comment by floflo37** [comment]
fini :smile:
