### ISSUE TITLE
Rubrique windows

### ISSUE THREAD

**Issue by loulou123546** [Info-Ormatique/website#11]
des balises qui n'existe pas, des pb de copier-coller, des balises non fermé, ... la page est à vérifié au peigne fin

**Comment by loulou123546** [comment]
+ la page windows qui elle aussi a des pb de codage

**Comment by floflo37** [comment]
Toutes ces pages vont être modifié dès que j'aurais les nouveaux fichiers

**Comment by floflo37** [comment]
problème de footeur #15 sur la première page Windows

**Comment by floflo37** [comment]
@loulou123546 
c'est pas a cause de tous les css

**Comment by floflo37** [comment]
c'est sur la page cmd

**Comment by floflo37** [comment]
![capture](https://cloud.githubusercontent.com/assets/28893730/26404893/bf5c6e18-4093-11e7-8649-64518505c1ee.PNG)

**Comment by loulou123546** [comment]
## De toute facon, les pages `windows.html` , `software security.html` et `cmd.html` ne respectent pas le design et doivent être re-codé en entier

**Comment by floflo37** [comment]
oui mais il faudrait quentin pour savoir un peu se qu'il voulait faire

**Comment by loulou123546** [comment]
il est en train de s'inscrire

**Comment by floflo37** [comment]
ok

**Comment by loulou123546** [comment]
## go to #26

**Comment by loulou123546** [comment]
tout ce passe sur la #26
