### ISSUE TITLE
Finir page ios

### ISSUE THREAD

**Issue by floflo37** [Info-Ormatique/website#16]
Changer la news dans la page iOS 
Une​ est sur Android dans la page iOS

**Comment by floflo37** [comment]
les liens des actus emmène vers d'autre site#

**Comment by loulou123546** [comment]
il me semblent que c'était voulu, non ?

**Comment by floflo37** [comment]
mais vers des site windows (pour le 1er)
dans les voir +

**Comment by mathyyg** [comment]
Je vais m'en occuper, je dois finir les 3 news, et les textes des menus déroulants, c'est prévu je m'en occupe

**Comment by loulou123546** [comment]
j'ai mis a jour les lien de la page `iosprincipale.html` car le footer bugger #25

**Comment by loulou123546** [comment]
## Bientôt fini ?! :angry:

**Comment by floflo37** [comment]
# Tu fini bientôt ? :rage:

**Comment by loulou123546** [comment]
# ***TU VAS NOUS REPONDRE SALOPE DE TES MORTS ?!***

**Comment by mathyyg** [comment]
J'suis en train de la finir tg

**Comment by loulou123546** [comment]
finis ?

**Comment by mathyyg** [comment]
C'est bouclé avant 22h

**Comment by floflo37** [comment]
il est 22h est c'est pas fini 😄

**Comment by mathyyg** [comment]
Tu joues sur les mots :)

**Comment by loulou123546** [comment]
J'aprouve @floflo37 ✔️ #remboursé

**Comment by mathyyg** [comment]
#fillonrendlargent

**Comment by loulou123546** [comment]
#bosse salope

**Comment by loulou123546** [comment]
on le vire ? @floflo37

**Comment by floflo37** [comment]
peut-être pas mieux vaut qu'il finisse

**Comment by loulou123546** [comment]
et demain on le vire à 10h

**Comment by loulou123546** [comment]
en parlant de ça, on en fait quoi après ? moi je veut bien récup le projet si personne en veut

**Comment by mathyyg** [comment]
bah franchement moi j'veux bien continuer, pas forcément InfoOrmatique ou forcément un site internet, mais si quelqu'un a un projet ça m'intéresse :+1:

**Comment by loulou123546** [comment]
j'ai un projet de navigateur web gratuit, sécurisé et anonyme

**Comment by loulou123546** [comment]
Simple Web :)

**Comment by loulou123546** [comment]
sinon ta fini ou pas ?

**Comment by mathyyg** [comment]
C'est avec grand plaisir que je vous annonce que j'ai TERMINÉ ma section iOS! :) ✔️
