### ISSUE TITLE
la page cmd.html a : 2 CSS et 1 image inexistant

### ISSUE THREAD

**Issue by loulou123546** [Info-Ormatique/website#18]
- style.css
- cmd.css
- Capture.JPG

Merci à @floflo37 d'avoir *correctement* supprimé les fichier 😠 
Pour la peine, tu verifira tout les fichier en `.html` !

**Comment by floflo37** [comment]
je dois les remettre quentin ma dis qu'ils servaient a rien

**Comment by floflo37** [comment]
normalement les fichier son de nouveau là
mais en tous cas il n'y avait pas d'image mais 3 css

**Comment by loulou123546** [comment]
ok, tu peut fermé si tu as fini, avec le petit ✔️ qui va bien

**Comment by floflo37** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/2714.png)

**Comment by loulou123546** [comment]
Juste pour Flo, apprend à faire le ✔️ ; tu écrit `:heavy_check_mark:`

**Comment by floflo37** [comment]
:heavy_check_mark:
