### ISSUE TITLE
bug script

### ISSUE THREAD

**Issue by floflo37** [Info-Ormatique/website#20]
dés que l'on écrit une lettre le "plus :arrow_down_small: " s'ouvre

**Comment by floflo37** [comment]
de plus la barre de recherche ne fonctionne pas
pour info on peut la voir sur w3-css

**Comment by loulou123546** [comment]
effectivement, c'est embêtant ! 😃

**Comment by floflo37** [comment]
oui un peu
sa ne sert pas à grand chose

**Comment by floflo37** [comment]
il marche pour toi

**Comment by loulou123546** [comment]
ah, je vien de découvrir que quand tu met le #20 dans un nom de ***commit***, sa ferme directement l'issue ! Du coup bug fixer ✔️

**Comment by loulou123546** [comment]
oui moi sa marche

**Comment by loulou123546** [comment]
fait F5

**Comment by loulou123546** [comment]
la preuve
![capture](https://cloud.githubusercontent.com/assets/20153343/26406166/cb512dc2-4097-11e7-8eef-54206c960402.PNG)

**Comment by floflo37** [comment]
c bon
tu pense que c'est bon pour la page android

**Comment by loulou123546** [comment]
le boutton pour cliquer sur le lien est trop petit, et en plus si le css pour le logo ne charge pas ( genre plus d'internet ) et bah tu pourra pas cliquer

**Comment by floflo37** [comment]
je vais mettre autre chose a cote

**Comment by floflo37** [comment]
c'est mieux

**Comment by loulou123546** [comment]
oui nickel, d'ailleurs quentin c'est nscrit, je l'ai invité, c'est @mamiegato

Du coup, l'issue est officiellement ✔️

**Comment by floflo37** [comment]
oui
je lui est parlé aussi

**Comment by floflo37** [comment]
tu t'occupe de lui expliquer si il ne connait pas encore
