### ISSUE TITLE
que pensez vous du nouveau message d'acceuil ?

### ISSUE THREAD

**Issue by loulou123546** [Info-Ormatique/website#22]
## dite moi ce que vous en pensez

aide : 
👍 -> `:+1:`
👎 -> `:-1:`

**Comment by floflo37** [comment]
tu parle de quel accueil

**Comment by loulou123546** [comment]
[ici](https://github.com/Info-Ormatique/website#website)

**Comment by floflo37** [comment]
:+1:

**Comment by loulou123546** [comment]
d'ailleurs j'ai fait explosé ton compteur de vue à + de 30 (+2 par secondes 😄 )

**Comment by floflo37** [comment]
sa fait pas tache?

**Comment by loulou123546** [comment]
je vait faire un script pour ajouter un max de vue

**Comment by floflo37** [comment]
OK de toute façon je crois qu'il ne marche pas il est toujours a 12

**Comment by loulou123546** [comment]
actualise

**Comment by loulou123546** [comment]
va voir le #23

**Comment by mathyyg** [comment]
👍

**Comment by loulou123546** [comment]
merci les gars 👏 ✔️
