### ISSUE TITLE
bug sur le compteur de visite

### ISSUE THREAD

**Issue by loulou123546** [Info-Ormatique/website#23]
le problème, c'est que le navigateur sauvegarde l'image pour pas avoir besoins de la recharger la fois d'après !

**Comment by floflo37** [comment]
j'en est un mieux

**Comment by loulou123546** [comment]
![capture](https://cloud.githubusercontent.com/assets/20153343/26409259/54d7d2b4-40a0-11e7-88d5-390f058f6806.PNG)

**Comment by floflo37** [comment]
il marche pas

**Comment by floflo37** [comment]
j'ai remis l'ancien

**Comment by floflo37** [comment]
![capture1](https://cloud.githubusercontent.com/assets/28893730/26409591/407cf802-40a1-11e7-9bc4-a36beea7c51f.PNG)

**Comment by loulou123546** [comment]
bcp de traffic aujourd'hui 😃 
![capture](https://cloud.githubusercontent.com/assets/20153343/26414244/da863f96-40ae-11e7-9def-4198e7d2c88b.PNG)

**Comment by floflo37** [comment]
tu as pas trafiquer un petit peu le compteur...

**Comment by loulou123546** [comment]
non, c'est juste que ton navigateur utilise l'ancienne image pour pas télécharger la nouvelle, sa optimise ton utilisation résaux

**Comment by loulou123546** [comment]
sinon on met pas de compteur ...

**Comment by floflo37** [comment]
oui

**Comment by floflo37** [comment]
plus de compteur
---> fini :fr: ✔️ 
```
<!--plus facile-->
<!-- c'est clair ! -->
```
