### ISSUE TITLE
vote design site

### ISSUE THREAD

**Issue by floflo37** [Info-Ormatique/website#24]
suite à #7 :
Pour le même design que l'[accueil](https://info-ormatique.github.io/website/index.html) ?
:+1:  --> oui
:-1:   -->non

**Comment by floflo37** [comment]
:+1:

**Comment by loulou123546** [comment]
👍 avec quelque modif au niveau de la taille du menu

**Comment by mathyyg** [comment]
👍

**Comment by loulou123546** [comment]
merci de votre vote ✔️
