### ISSUE TITLE
footeur bug en mode telephone

### ISSUE THREAD

**Issue by floflo37** [Info-Ormatique/website#25]
![2017-05-25_151041](https://cloud.githubusercontent.com/assets/28893730/26451442/577b75ae-415c-11e7-8bfc-e74f5fb86d47.jpg)

**Comment by floflo37** [comment]
@loulou123546 
pourrait tu regarder

**Comment by loulou123546** [comment]
ok, je regarde ce que je peut faire

**Comment by loulou123546** [comment]
le footer refonctionnent ✔️ , sauf pour les pages : 
- ***iospagenews1***
- ***windows***
- ***cmd***
- ***software security***

car elle sont non fonctionnelle

**Comment by floflo37** [comment]
tout fonctionne ☑️
