### ISSUE TITLE
changement du design des fichier de quentin

### ISSUE THREAD

**Issue by loulou123546** [Info-Ormatique/website#26]
@mamiegato n'étant pas là 😠 , je vais recodé `windows.html`, `cmd.html`, et `software security.html`.

Je laisse le texte est les image mais je rajoute le menu et les différents élement commun aux différentes page

**Comment by loulou123546** [comment]
quentin ma dit qu'il le fait, aujourd'hui, sinon je le fait demain

**Comment by loulou123546** [comment]
pour `windows.html`, c'est fait #28

**Comment by mamiegato** [comment]
j'tais la mais pas à ce moment-là

**Comment by loulou123546** [comment]
finish :heavy_check_mark:
