### ISSUE TITLE
problème page Windows

### ISSUE THREAD

**Issue by floflo37** [Info-Ormatique/website#3]
le plus se cache sous l'image

**Comment by loulou123546** [comment]
sur chrome, la page semblent marché :
![capture](https://cloud.githubusercontent.com/assets/20153343/26354622/aa9fc2fa-3fc5-11e7-8a0b-8037ea5f7831.PNG)

**Comment by loulou123546** [comment]
demande de cloture de l'issue

**Comment by floflo37** [comment]
:gb:
