### ISSUE TITLE
changer certain icone du head

### ISSUE THREAD

**Issue by floflo37** [Info-Ormatique/website#30]
J'ai trouver 2 icône autre que ceux présent pour le moment pour:
[Windows](https://github.com/Info-Ormatique/website/blob/master/IMG/windows.png)
[IOS](https://github.com/Info-Ormatique/website/blob/master/IMG/apple.png)
Ces 2 images sont sur font transparent contrairement a celle présente sur la page IOS et la page Windows  comporte celui de l'accueil.
si vous êtes ok --> 👍 
sinon --> 👎

**Comment by mathyyg** [comment]
ça me va!

**Comment by floflo37** [comment]
du coup je vais changer le logo iOS et je vais attendre Quentin pour ce celui de Windows

**Comment by floflo37** [comment]
d'ailleurs j'ai actualisé tes liens de tes 2 pages

**Comment by floflo37** [comment]
et Louis en a fait un peu

**Comment by loulou123546** [comment]
# 👍 Carrément ok

**Comment by floflo37** [comment]
je vais attendre Quentin pour sa page
mais pour le moment je l'ai changé sur Android et sur iOS

**Comment by floflo37** [comment]
fait sur les 2 pages ✔️
