### ISSUE TITLE
partie en rouge dans le menu

### ISSUE THREAD

**Issue by loulou123546** [Info-Ormatique/website#31]
Pour le menu, vous préferé que le lien en rouge soit : 
- :-1: toujours l'accueil
- 👍 la page sur laquelle on est actuellement

**Comment by loulou123546** [comment]
perso, 👍 sa fait plus pro

**Comment by floflo37** [comment]
👍 c'est vrai mais il faudrait mettre un truc a l'icone de l'accueil pour que si il s'affiche pas il y a écrit "home" à la place car sinon on voit une case blanche

**Comment by loulou123546** [comment]
ou on passe le logo en noir sur toute les pages sauf l'acueil

**Comment by mathyyg** [comment]
👍

**Comment by mathyyg** [comment]
Du coup?

**Comment by floflo37** [comment]
je pense qu'on le mettra sur la page du menu où on est

**Comment by floflo37** [comment]
close :fr:
