### ISSUE TITLE
organisation pour la présentation de demain

### ISSUE THREAD

**Issue by loulou123546** [Info-Ormatique/website#38]
Qui présente quoi ? Vous avez à présenter : 

- ✔️  les pages du site :
  - ✔️  accueil `@floflo37`
  - ✔️  windows (+ cmd si fini) `@mamiegato`
  - ✔️  IOS        `@mathyyg`
  - ✔️  android   `@floflo37`
  - ✔️  configOtop    `@valou-21`
- ✔️  technologie utilisé
  - ✔️  HTML 5 / CSS 3 / JavaScript   *(simple)*  `@mamiegato`
  - ✔️  w3.css `@floflo37`
    - ✔️  quesque c'est ?
    - ✔️  pourquoi l'utiliser
    - ✔️  avantages / inconvénient (si il y en a 😄 )
- ✔️  ***question sur github*** `@loulou123546`
  - ✔️  présenter Github `@mathyyg`
    - ✔️  c'est quoi ?
    - ✔️  sa sert à quoi ?
    - ✔️  montrer le projet + fonctionnement de Github (issue, code, ...)
    - ✔️  avantages / inconvénient
- ✔️  conclusion `tous, @valou-21`

### **Bon courage !** 👍

*ps: laisser l'issue ouverte jusque demain*

**Comment by loulou123546** [comment]
écrivez en commentaire ce que vous souhaitez présenter

**Comment by floflo37** [comment]
je veux bien faire la technologie w3-css et l'accueil si personne ne le fait

**Comment by loulou123546** [comment]
ok flo

**Comment by floflo37** [comment]
au pire on verra demain matin avant l'icn

**Comment by loulou123546** [comment]
tu veut faire tout le w3.css ?

**Comment by floflo37** [comment]
sauf si quelqu'un veut le faire

**Comment by floflo37** [comment]
pour les 3 technologie restante on pourra les faire avec les pages

**Comment by loulou123546** [comment]
c'est pas le plus important les technos, c'est surtout qui prend la charge de présenter github

**Comment by mathyyg** [comment]
Je peux présenter Github

**Comment by loulou123546** [comment]
tu fait tout ou tu coupe en deux avec un autre ?

**Comment by mathyyg** [comment]
Je fais tout

**Comment by mathyyg** [comment]
Si flo s'occupe du w3.css, et moi de la présentation de Github, quentin et val peuvent s'occuper de présenter rapidement les 4 pages, les liens, l'accueil, etc... l'aspect "visuel"

**Comment by loulou123546** [comment]
j'ai terminé le plan, sa vous va ? (on le travaillera avec valou et quentin demain matin avant l'ICN)

**Comment by mathyyg** [comment]
ça me va, on verra demain matin avec tout le monde au CDI!

**Comment by floflo37** [comment]
si tout le monde vient au CDI à 8h ont pourra voir

**Comment by mathyyg** [comment]
oui

**Comment by loulou123546** [comment]
bon boulot les gars 👍 , les issues sont finis ?

**Comment by mathyyg** [comment]
je mange un truc vite def et je finis mes news ios (5-10 minutes GRAND MAX.)
le reste ce sont windows je crois

**Comment by loulou123546** [comment]
niquel, pour windows il reste que le `cmd.html` mais au pire on le présente pas

**Comment by loulou123546** [comment]
# FELICITATION, ON A TOUT FINI A TEMPS :)  BRAVO A TOUS :champagne: 😄 
![capture](https://cloud.githubusercontent.com/assets/20153343/26561586/d95c8e1c-44bf-11e7-9e3b-e93def43e07d.PNG)

**Comment by floflo37** [comment]
# présentation faite
