### ISSUE TITLE
manque 2 news sur windows

### ISSUE THREAD

**Issue by floflo37** [Info-Ormatique/website#39]

**Comment by loulou123546** [comment]
c'est trop tard, il faut mettre de fausse news ou alors quelqu'un d'autres s'en occupe

**Comment by floflo37** [comment]
il faudrait prendre des news sur Google news

**Comment by mathyyg** [comment]
On a plus le temps, tu mets des trucs vite fait

**Comment by floflo37** [comment]
appart si quelqu'un veut le faire je le ferait demain matin soit à 8h soit avant

**Comment by floflo37** [comment]
résolut
