### ISSUE TITLE
le compteur de vue

### ISSUE THREAD

**Issue by loulou123546** [Info-Ormatique/website#40]
@floflo37 c'est bien marrant de jouer avec le compteur de vue 😄 , mais sa fait vraiment tache sur une seul page ... alors on fait quoi ?

**Comment by mathyyg** [comment]
On s'en fout? :)

**Comment by floflo37** [comment]
on le vire?

**Comment by loulou123546** [comment]
c'est pas un bug, c'est un ... easter egg ! 😃
