### ISSUE TITLE
unifier le design du site

### ISSUE THREAD

**Issue by loulou123546** [Info-Ormatique/website#7]
La moitié du site est à peut près **material design**, tandis que l'autre est noir et orange !

De plus, certaine page ne sont page affiché dans la barre du menu, sont t-elle supprimé ? ou oublié ?

Bref, il serait temps de vous mettre d’accord sur les couleur, et de tous utiliser le w3.css (hein quentin)

**Comment by floflo37** [comment]
c'est normal certain fichier ne sont pas a jour car je ne les possède pas

**Comment by loulou123546** [comment]
ok, puisque il y a pas tout les fichiers, je vais attendre pour les trié dans les dossiers

**Comment by loulou123546** [comment]
faut que l'on réfléchisse au design final du site

**Comment by mathyyg** [comment]
c'est quentin qui doit mettre sa page avec du w3.css, nous on a tout on modifie juste les textes

**Comment by loulou123546** [comment]
bon, si @mamiegato répond pas avant ce soir, c'est moi qui refait sa page 😠

**Comment by loulou123546** [comment]
## see #26 pour les pages de quentin

**Comment by floflo37** [comment]
# vote pour le design #31

**Comment by loulou123546** [comment]
c'est enfin ***close*** :heavy_check_mark:
