### ISSUE TITLE
URGENT /!\ : plusieurs body dans le même fichier !

### ISSUE THREAD

**Issue by loulou123546** [Info-Ormatique/website#8]
Dans quasiment tout les fichier, on trouve :

```html
<body>
	<!--couleur de fond-->
	<BODY BGCOLOR="#000000">
```

et en plus, un seul des deux est refermé, laissant donc une balise ouverte

---

⚠️ Petite explication : la balise `<body>` sert à délimité le html qui doit être affiché dans la page.

**Comment by loulou123546** [comment]
au passage, je pense que les 2 body sont liée à ce bug : 
![capture](https://cloud.githubusercontent.com/assets/20153343/26372879/ab41e74e-3fff-11e7-9ae8-b6aef2947861.PNG)

**Comment by floflo37** [comment]
avec mathys on a vu un truc qui marche pour résoudre se problème mais je n'ai pas le code de resolution avec moi

**Comment by floflo37** [comment]
pour le rangement tu me la dit que tu le faisait

**Comment by floflo37** [comment]
problème body résolu

**Comment by loulou123546** [comment]
ok, finsh and closed ✔️
