### ISSUE TITLE
icone title du head a modifier

### ISSUE THREAD

**Issue by floflo37** [Info-Ormatique/website#9]
config o top à le symbole Apple

**Comment by loulou123546** [comment]
il doit avoir le logo d'apple, ou le logo habituel ?

**Comment by floflo37** [comment]
il faudrait mettre un logo en rapport avec la page

**Comment by loulou123546** [comment]
normallement, un site = un logo, pas 2 ni 3

**Comment by loulou123546** [comment]
le logo n'est pas la priorité, donc fini ✔️
